// Participantes del sorteo del viaje a París — Lanzamiento Mayo 2026
export const SORTEO_PARTICIPANTS: string[] = [
  'Alicia Soria',
  'Natalia Bienestar Emocional & Transformación',
  'teretahoe',
  'Irene',
  'Macarena - Setter y Closer de ventas',
  'Patricia Carranza Gomollón',
  'AROUSA FLATS City&Beach',
  'ANGELICA MELO | MAQUILLADORA',
  'Zelai | Claridad & Decisión',
  'Marsou Marsou',
  'Raquel Pérez Alonso',
  'ro',
  'Miriam | Estratega de Conducta y Bienestar',
  'Reme Molina | Real Estate',
  'SONIA SANCHEZ',
  'Bea Domínguez',
  'Vir Xispi',
  'veroó',
  'Selene Brito',
  'Yol Ypower',
  'Rebeca Andrade | Pérdida de peso +40',
  'Miriam Lorenzo | Desarrollo personal',
  'Dayana',
  'Marta Ruiz | Art Dealer | Art Manager',
  'Mercedes Gómez',
  'Laura Ramirez | Estética Integral & Formacio...',
  '_criistinaa94',
  'Lorena',
  'Coach Fitness Online | Valeria Verazzo',
  'Luiza',
  'Lydia Arevalo | Nail Creator',
  'Alkimia Design',
  'Lorena 💖',
  'evamaria___',
  'Candy | Bienestar & Vida real',
  'Patricia Calaco Mulero',
  'Génesis',
  'Josefina Martos | Mama Real',
  'Peluquería Entrebambalinas',
  'Lucía Arévalo | Escuela de Floristería',
  '🌈 Tammy · E S S E N C E & INTUITION ✨',
  'Rocío | Coach en Salud Hormonal',
  'Tammy / Borboleta 🦋',
  'Atala | Profesora de Inglés hablado para p...',
  'Cris Nieto | Lipedema',
  'Cristina Lamor | Equilibrio Consciente 🌸',
  'laurafrlz',
  'Bea Castejón',
  'Sara',
  'Glaidimar Ceballos',
  'Ane Maruri',
  'ROSA LÓPEZ | FORMADORA ONLINE',
  'Lorena Herrera | Reconexión femenina & Espi...',
  'Mary Ann León · Estrategia Digital',
  'Marta Castro Fernández',
  'Alejandra',
  'Yurena | Bienestar | Emprende mami',
  'Vane',
  'Celia Isabel Raulea',
  'SAM 🦋',
  'Almu 🐱🐱🐶🐶',
  'Pamela Mosquera',
  'PATRICIA RAMOS',
  'Carmen',
  'Alexandra',
  'Nerea Rocha',
  'Raquel Ferrández / Nutrición Perimenopausi...',
  'Sonia Guerrero',
  'Nerea',
  'Marta Gomez | Nutricion Emocional',
  'Aiko Ave',
  '✨Angelica🌺',
  'virgcb',
  'Elga Gil | Fundadora CHICASDE50',
  'Dulce | Diario de un proceso',
  'Marzela Diaz',
  'Con Eva en Redes | Gestion y Marketing Digital',
  'Andrea | Fluidez en Inglés para el Trabajo',
  'MARINA MOYA',
  'Paola',
  'Maria Luisa Riquelme Coach',
  'TANIA ARIZA – Coach nutricion y bienestar',
  '✨ Lorena Marín – Formadora & Tatuadora ✨',
  'Alisson',
  'mari',
  'Gina Theresa Edvardsen',
  'MÓNICA ADSUAR',
  'CURSOS EXTENSIONES DE PESTAÑAS | LAS...',
  'Cristina Ghinescu | NETWORKER',
  'Puri Muñoz Iglesias',
  'María Álvarez',
  'AMS',
  'Dra Judith Fen | Neurociencia y Alma',
  'Zayra',
  'Kris Cia',
  'Katy – Coach y Practitioner en PNL, certifica...',
  'Más Energía 💪 40 +',
  'Purita Correas/IA',
  'Karen G Monfort',
  'Noemí | Cuidado personal',
  'Blanca Abenia Pera',
  'Belen Camaño | Marketing digital',
  'Cristina Serrato🦋 Comunicadora del Alma & ...',
  'Tania Molina | Piel sensible +35🌿',
  'nnnicolgomez',
  'JUDITH B | LIDERAZGO Y LIBERTAD',
  '✨Valeria✨',
  'YANINA RICCI 🌺',
  'Inmaculada De Saray',
  'Susana Gil Ruiz',
  'Lorena Da Silva Estevez',
  'Patricia Puerta - Logopeda y Formadora d...',
  'Meri Hovsepyan',
  'Natalia Álvarez',
  'Olga Vida',
  'Maria Gabriela Knudsen Rodriguez',
]
